modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="deadlymining"
version="1.0.0"
displayName="DeadlyMining"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Oskar W. Heineck, MCreator"

[[dependencies.deadlymining]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




